spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


spring.devtools:
  restart:
    enabled: true

server:
  servlet:
    context-path: /oslc/services
  port: 8081

logging:
  level:
    root: INFO


data:
  path: localhost:8080/neo4j
